name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  dotnet-tasks:
    strategy:
      matrix:
        task:
          - command: restore
            projects: '**/*.csproj'
            nugetConfigPath: 'NuGet.config'

          - command: build
            projects: '**/*.csproj'
            arguments: '--configuration Release'

          - command: test
            projects: '**/*.csproj'
            arguments: '--collect "Code coverage"'

          - command: pack
            packagesToPack: '**/*.csproj'
            configuration: 'Release'

    uses: kirandevops1993/.NET-REUSBALE/.github/workflows/reusable.yml@main
    with:
      command: restore
      projects: '**/*.csproj'
      arguments: '--configuration Release'
      nugetConfigPath: 'NuGet.config'
      packagesToPack: '**/*.csproj'
      configuration: 'Release'
      custom: 'true'
      restoreArguments: '--interactive'
      testRunTitle: 'CI Test Run'
      modifyOutputPath: 'true'
      packDirectory: './custom_pack'
      nobuild: 'true'
      includesymbols: 'true'
      includesource: 'true'
      requestTimeout: '180'
      noCache: 'true'
      restoreDirectory: './restoredir'
      verbosityRestore: 'minimal'
      publishPackageMetadata: 'true'
      versioningScheme: '1.0.0'
      versionEnvVar: 'BUILD_VERSION'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '3'
      buildProperties: 'CommitId=abc123'
      verbosityPack: 'detailed'
      workingDirectory: './src'
